### ISSUE TITLE
Trying to create linux portable distribution

### ISSUE THREAD

**Issue by sonoro1234** [luapower/luapower-all#2]
Hello Cosmin,

I have a project (https://github.com/sonoro1234/anima) that managed to compile as portable for windows with mingw and msvc also. Now I got access (for the first time) to an Ubuntu system and I was trying to achieve the same goal, but when I do `ffi.load"glfw"` an error message is saying `cannot open shared object file: No such file or directory` remembering windows I guess that some runtime libraries are missing in the directory. Also I saw that in luapower-all you distribute libgcc... , libstdc++... and perhaps some others. Is this the cause of my error? What should be the libraries to put on the directory? Could this be done in a CMake build (programatically)?

Thanks for your attention.
Victor Bombi

**Comment by capr** [comment]
Hi, 

glfw is not in luapower, so I suppose you built it yourself? If so, you need to have the binary on Linux too of course, along with everything else.

**Comment by sonoro1234** [comment]
It seems that I dont have it. May be I will try to compile an glfw C example to see if something happens!!

**Comment by sonoro1234** [comment]
Compilation worked giving no clues!!
But `ffi.load"./libglfw.so"` works and `ffi.load"libglfw.so"` or `ffi.load"glfw"` dont, athought in luapower-all `ffi.load"cairo"` is working.
What can it be the problem?

**Comment by capr** [comment]
that only works if the lib is in the dir of the main exe and if you set
rpath when linking. look at a few build scripts to see how it's done.

**Comment by sonoro1234** [comment]
If I put libglfw.so in luapower-all/bin/linux64 I can ffi.load it!!

rpath must be the key, I didnt know anythig about it!!
Where should it point to? When linking what? glfw, luajit...
I found https://amir.rachum.com/blog/2016/09/17/shared-libraries/
So it seems I should link luajit with rpath pointing to executable directory as `-Wl,-rpath,"\$ORIGIN"`
this seems to be done in luajit building with PREFIX somehow but my knowledge of Makefiles is very low to guess how.
Just found https://luapower.com/building. I will dig into it.

**Comment by sonoro1234** [comment]
Your clue about setting rpath was the key for solving the problem. I would have never guessed that, being a newcommer to linux programming. Just solved the issue setting LD_LIBRARY_PATH with the same script that is setting LUA_PATH and LUA_CPATH

Thank you very much!!
