### ISSUE TITLE
x86 (x32) why not?

### ISSUE THREAD

**Issue by dr-dba** [luapower/luapower-all#4]
Hello Cosmin, and thank you for your great work.
Together with that, why no x32 distribution, particularly for windows?
It is kind of showstopper for me, i have a number of hosts with mixed architecture

**Comment by capr** [comment]
hi, 32bit binaries and build scripts were removed sometime ago simply as a matter of priority for me, since I am the solo dev on the project. You'll have to grab them from git history and maintain them yourself if you need them.

**Comment by dr-dba** [comment]
as a matter of help with the project, how i probably can help you?

lets say, i have built LuaCom for x64, this seems to be the one and only
x64 LuaCom in the world

either which help you may accept?
